/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        "on-secondary-container": "#5c636c",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#404750",
        "on-primary-fixed-variant": "#004493",
        "on-primary-fixed": "#001a41",
        "tertiary": "#9e4300",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-surface": "#191c1d",
        "primary-fixed": "#d8e2ff",
        "on-error-container": "#93000a",
        "outline-variant": "#c1c6d6",
        "background": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "secondary": "#585f68",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dce3ed",
        "surface-variant": "#e1e3e4",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#adc7ff",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed-dim": "#ffb691",
        "surface-container": "#edeeef",
        "surface-tint": "#005bc0",
        "secondary-container": "#d9e0eb",
        "on-secondary-fixed": "#151c24",
        "on-tertiary-fixed-variant": "#783100",
        "outline": "#727785",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadb",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#c0c7d1",
        "primary": "#005bbf",
        "on-tertiary-container": "#0e0200",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "primary-container": "#1a73e8",
        "tertiary-container": "#c55500",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-fixed": "#341100",
        "primary-fixed-dim": "#adc7ff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#414754",
        "surface-container-high": "#e7e8e9",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
      },
      spacing: {
        "stack-md": "16px",
        "gutter": "24px",
        "section-gap": "48px",
        "unit": "4px",
        "stack-sm": "8px",
        "stack-lg": "24px",
        "container-padding": "32px",
      },
      fontFamily: {
        "h2": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "mono-label": ["Inter"],
        "label-sm": ["Inter"],
        "h1": ["Inter"],
        "h3": ["Inter"],
        "dm-sans": ["DM Sans", "sans-serif"],
        "instrument": ["Instrument Serif", "serif"],
      },
      fontSize: {
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "mono-label": ["13px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h3": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.375rem",
        sm: "0.25rem",
        xl: "0.75rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
